### ISSUE TITLE
[Suggestion] Hoarder's and Collector's Distillation for Entities

### ISSUE THREAD

**Issue by JohnDog3112** [Cypher121/hexbound#10]
It would be nice if there was an extension or set of patterns equivalent to the Hoarder's and Collector's Distillation Patterns for entities like chest minecarts and boat chests. Either as a whitelist or just finding entities that can interact with hoppers. I'm posting it here just in case there's a chance of it being added to 1.19. However, since I've been told moreiotas is taking these patterns in 1.20 I'm going to post this suggestion [there](https://github.com/Talia-12/MoreIotas/issues/15) too.

**Comment by Cypher121** [comment]
There won't be more Hexbound releases for 1.19.2, so it's up to MoreIotas to handle that for 1.20 now
