### ISSUE TITLE
Mod Lists as 1.19-1.19.3 but uses only 1.19.3 QSL

### ISSUE THREAD

**Issue by emoace** [Cypher121/hexbound#2]
Crash Log lists "hexcasting" as the source of the crash but it loads fine if I have Hexbound disabled.

Crash Log:

<details>
  <summary>Click me</summary>
  

> Description: Initializing game java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'hexcasting'! 	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$2(EntrypointUtils.java:63) 	at org.quiltmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) 	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:61) 	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invokeContainer(EntrypointUtils.java:46) 	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:33) 	at org.quiltmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52) 	at net.minecraft.class_310.<init>(class_310.java:459) 	at net.minecraft.client.main.Main.method_44604(Main.java:205) 	at net.minecraft.client.main.Main.main(Main.java:51) 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 	at java.base/java.lang.reflect.Method.invoke(Method.java:568) 	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:423) 	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:76) 	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:24) 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 	at java.base/java.lang.reflect.Method.invoke(Method.java:568) 	at org.prismlauncher.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104) 	at org.prismlauncher.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:176) 	at org.prismlauncher.impl.OneSixLauncher.launch(OneSixLauncher.java:186) 	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:144) 	at org.prismlauncher.EntryPoint.main(EntryPoint.java:74) Caused by: java.lang.BootstrapMethodError: java.lang.RuntimeException: Mixin transformation of at.petrak.hexcasting.api.spell.casting.CastingHarness failed 	at at.petrak.hexcasting.common.items.magic.ItemCreativeUnlocker.<clinit>(ItemCreativeUnlocker.java:67) 	at at.petrak.hexcasting.common.lib.HexItems.<clinit>(HexItems.java:96) 	at at.petrak.hexcasting.common.lib.HexBlocks.blockItem(HexBlocks.java:217) 	at at.petrak.hexcasting.common.lib.HexBlocks.<clinit>(HexBlocks.java:124) 	at at.petrak.hexcasting.fabric.FabricHexInitializer.initRegistries(FabricHexInitializer.kt:92) 	at at.petrak.hexcasting.fabric.FabricHexInitializer.onInitialize(FabricHexInitializer.kt:49) 	at org.quiltmc.loader.impl.game.minecraft.Hooks.lambda$startClient$0(Hooks.java:52) 	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke$0(EntrypointUtils.java:33) 	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:59) 	... 22 more Caused by: java.lang.RuntimeException: Mixin transformation of at.petrak.hexcasting.api.spell.casting.CastingHarness failed 	at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:283) 	at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:153) 	at org.quiltmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:156) 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520) 	... 31 more Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) 	at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:278) 	... 34 more Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Callback method hexbound$failForbiddenConstructSpells(Lat/petrak/hexcasting/api/mod/HexConfig$ServerConfigAccess;Lnet/minecraft/class_2960;Lcom/llamalad7/mixinextras/injector/wrapoperation/Operation;)Z in hexbound.mixins.json:CastingHarnessMixin from mod hexbound failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap hexbound-refmap.json 	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468) 	at com.llamalad7.mixinextras.injector.wrapoperation.WrapOperationInjectionInfo.lateApply(WrapOperationInjectionInfo.java:40) 	at com.llamalad7.mixinextras.injector.wrapoperation.WrapOperationApplicatorExtension.postApply(WrapOperationApplicatorExtension.java:34) 	at org.spongepowered.asm.mixin.transformer.ext.Extensions.postApply(Extensions.java:167) 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.postApply(TargetClassContext.java:432) 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:405) 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) 	... 37 more A detailed walkthrough of the error, its code path and all known details is as follows: --------------------------------------------------------------------------------------- -- Head -- Thread: Render thread Stacktrace: 	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$2(EntrypointUtils.java:63) 	at org.quiltmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) 	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:61) 	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invokeContainer(EntrypointUtils.java:46) 	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:33) 	at org.quiltmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52) 	at net.minecraft.class_310.<init>(class_310.java:459)

</details>

**Comment by Cypher121** [comment]
Oh, it's not supposed to use the version modrinth says it does, latest 1.19.2 QSL will do fine. I'll update the modrinth version dependencies.

**Comment by Cypher121** [comment]
Modrinth version now has correct dependency versions and the game version listed as 1.19.2

**Comment by Cypher121** [comment]
Crash itself also fixed in beta.2
