### ISSUE TITLE
Hexbound lists unavaliable version of Geckolib as a requirement (1.19.2)

### ISSUE THREAD

**Issue by noukherne** [Cypher121/hexbound#7]
Been trying to install the latest version. 0.1.2 is listed as being avaliable for 1.19.2-1.19.3 but requires geckolib 4.0.6 which is only avaliable on 1.19.3+. 

It starts up with an older geckolib version, but crashes on load with something I'm pretty sure is related to the new shield. Could this be just a versioning error?

Will try to provide some logs later if needed, I'm not sure how generalized this error is.

**Comment by noukherne** [comment]
[crash-2023-04-12_19.07.40-client.txt](https://github.com/Cypher121/hexbound/files/11214160/crash-2023-04-12_19.07.40-client.txt) 

There's the logs, good to know about the versioning.

**Comment by noukherne** [comment]
Alright, thanks for the help. Will wait for the next version

**Comment by Cypher121** [comment]
Fixed as of [0.1.3](https://modrinth.com/mod/hexbound/version/0.1.3+1.19.2)
