### ISSUE TITLE
Figment bind on a cleric impetus clears upon chunk reload.

### ISSUE THREAD

**Issue by computer-whisperer** [Cypher121/hexbound#8]
Seen on the hexxycraft server. The figment bind seems to work fine while the chunks are force-loaded, but if the force-load is removed then the impetus seems to completely unbind from the figment and requires a new figment bind to function again.

**Comment by Cypher121** [comment]
Not sure as to the cause, and with 1.20 changes around the corner I don't know if I will be fixing it.
