### ISSUE TITLE
Hexbound not loading in for Fabric Modpack 1.19.2.

### ISSUE THREAD

**Issue by ViaBeans** [Cypher121/hexbound#9]
I have the mod enabled on a modpack with hexal and hexcasting, and looking through the logs it doesnt seem to have even loaded in. No items, no entries in the hex book.

Here is the log.
[latest.log](https://github.com/Cypher121/hexbound/files/11898141/latest.log)

**Comment by Cypher121** [comment]
This is a [Quilt](https://quiltmc.org) mod, it will not load on Fabric.
